#!/usr/bin/python

from zigdiggity.datastore import database_session
from zigdiggity.datastore.networks import Network
from zigdiggity.datastore.devices import Device

for device in database_session.query(Device).all():
    database_session.delete(device)

for network in database_session.query(Network).all():
    database_session.delete(network)

database_session.commit()
